### ISSUE TITLE
KokkosBlas::gemv and gemm no longer compile with mixed CudaSpace and CudaUVMSpace views.

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos-kernels#1913] opened 2023-07-25 16:08 UTC
We have previously used KokkosBlas::gemv and gemm with A being a matrix in CudaSpace and x/y (or b/c for gemm) being in CudaUVMSpace. As of the most recent snapshot to Trilinos this now fails to compile due to the static_asserts that check SpaceAccessibility<...>::assignable.

@lucbv

**Comment by lucbv** [comment] 2023-07-25 17:10
Thanks for reporting this @vbrunini I would have thought that CudaUVMSpace is assignable from the Cuda execution space?
I will talk with the Kokkos Core team and clarify that, in general the new assertion is there to make sure that users do not pass something that is stored in HostSpace with a device execution space.

**Comment by lucbv** [comment] 2023-07-25 17:13
Ah, actually the issue is with `assignable` vs `accessible` that makes sense, my bad for misunderstanding, will get that fixed.

**Comment by lucbv** [comment] 2023-07-25 17:38
Okay, should be addressed in PR #1914

**Comment by vbrunini** [comment] 2023-07-25 17:40
Thanks!

**Comment by lucbv** [comment] 2023-07-28 23:37
Can you check that everything works fine now that #1914 was merged?
If so we can close this issue.

**Comment by vbrunini** [comment] 2023-08-01 14:50
I think the change looks good, but it will be a bit before I get a chance to test it in sierra. Could you add a kokkos-kernels test for the mixed memory space usage? I think if you do that it's safe to close this before I get a chance to test in the app.

**Comment by lucbv** [comment] 2023-08-01 15:23
I can add such a test but we will have to be a bit careful with it as it requires the flag `KOKKOSKERNELS_TEST_ETI_ONLY=OFF` and this is only tested in [one](https://jenkins-son.sandia.gov/view/KokkosKernels/job/KokkosKernels_PullRequest_GNU1021/) of our CI builds and it is running on CPU...
I'll discuss with others to see if we can add such a build on GPU but we might simply not have the testing capacity for it, we need to check.

**Closed** 2023-11-27 18:17 UTC
Labels: bug, InDevelop
