### ISSUE TITLE
CUDA and HIP runtime API: surround calls with hip_internal_safe_call or cuda_internal_safe_call as in Kokkos

### ISSUE THREAD

**Issue by romintomasetti** [kokkos/kokkos-kernels#1428] opened 2022-05-27 09:45 UTC
When compiling Trilinos, I get a lot of warning messages from `src/common/KokkosKernels_ExecSpaceUtils.hpp` that some return code is not used, like the following:
```c++
          /home/***/Trilinos/packages/kokkos-kernels/src/common/KokkosKernels_ExecSpaceUtils.hpp:371:5: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
         hipMemGetInfo(&free_mem, &total_mem);
         ^~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
```

An easy fix might be to use the Kokkos macros:
* `KOKKOS_IMPL_CUDA_SAFE_CALL` from https://github.com/kokkos/kokkos/blob/master/core/src/Cuda/Kokkos_Cuda_Error.hpp
* `KOKKOS_IMPL_HIP_SAFE_CALL` from https://github.com/kokkos/kokkos/blob/master/core/src/Cuda/Kokkos_HIP_Error.hpp

This would remove compiler warnings and also improve robustness.

**Comment by romintomasetti** [comment] 2022-05-27 09:46
Note: this might be a duplicate of https://github.com/kokkos/kokkos-kernels/issues/1347.

**Comment by lucbv** [comment] 2022-07-06 23:31
@romintomasetti this is indeed a duplicate of #1347 so I will close this issue.
Note that I have opened a PR that should clean these warnings, see #1459

**Closed by lucbv** 2022-07-06 23:31 UTC
