### ISSUE TITLE
Failing tests when float is enabled

### ISSUE THREAD

**Issue by mndevec** [kokkos/kokkos-kernels#97] opened 2017-10-03 23:40 UTC
Below are the tests reported by @kyungjoo-kim . I get a smaller subset of below failures on different machines. These are mainly epsilon errors.

[ FAILED ] 14 tests, listed below:
[ FAILED ] openmp.abs_float
[ FAILED ] openmp.abs_mv_float
[ FAILED ] openmp.nrm2_squared_float
[ FAILED ] openmp.nrm2_squared_mv_float
[ FAILED ] openmp.reciprocal_mv_float
[ FAILED ] openmp.scal_mv_float
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int_int_LayoutLeft_TestExecSpace
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int64_t_int_LayoutLeft_TestExecSpace
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int_size_t_LayoutLeft_TestExecSpace
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int64_t_size_t_LayoutLeft_TestExecSpace
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int_int_LayoutRight_TestExecSpace
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int64_t_int_LayoutRight_TestExecSpace
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int_size_t_LayoutRight_TestExecSpace
[ FAILED ] openmp.sparse_trsv_mv_kokkos_complex_float_int64_t_size_t_LayoutRight_TestExecSpace

**Comment by ndellingwood** [comment] 2018-10-12 21:51
Issue #322 turns out to be a duplicate of this one. I'm closing this in favor of that issue where I'm actively working on resolving it.

**Closed by ndellingwood** 2018-10-12 21:51 UTC
Labels: bug, duplicate
