### ISSUE TITLE
Nightly build failures with cuda/11.0: nvcc error   : 'cicc' died due to signal 11

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1943] opened 2023-08-15 17:42 UTC
The nightly cuda/11.0 build is failing to compile with an apparent internal compiler error:

```
02:16:45 nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)
02:16:45 nvcc error   : 'cicc' core dumped
02:16:45 make[2]: *** [sparse/unit_test/CMakeFiles/KokkosKernels_sparse_cuda.dir/backends/Test_Cuda_Sparse.cpp.o] Error 139
```

This is the set of changes merged when this type of failure begain:

Git (git https://github.com/kokkos/kokkos.git)

    subset of team level impl of std algorithms (detail)
    fix copyright (detail)
    guard for openmptarget (detail)
    fix for openmptarget (detail)
    address comments (detail)
    std_algos: for_each: try condense the impl (detail)
    format (detail)
    Enforce create_mirror restrictions w.r.t. ViewCtorArgs on all variants (detail)
    Use KOKKOS_IF_ON_HOST (detail)
    Suppress warnings (detail)
    Don't suppress warnings for NVHPC (detail)
    Improve macro definitions (detail)
    bring back previous code as discussed in meeting (detail)
    Add comment that we don't need to link against clang_rt with ROCm 5.5 (detail)
    Error out when CXX standard is not set when using amdclang or cray clang (detail)
    Disable failing tests for ROCm 5.5 and 5.6 (detail)
    Fix reviewer's comments (detail)
    remove spurious undefs (detail)
    Decrease maximum memory available to ccache (detail)
    Fix gtest when using C++20 (detail)
    Fully qualify Experimental::SYCL in algorithms to avoid conflicting namespaces (detail)
    SIMD: split simd unit tests into separate files (#6278) (detail)
    Run NVHPC only on V100 (detail)
    Use checked arithmetic builtins for overflow detection (#6313) (detail)
    Passing size==0 to DeepCopy/memcpy/omp_target_memcpy (#6273) (detail)
    allow sorting via native oneDPL  to support views with stride = 1 (#6322) (detail)

Git (git https://github.com/kokkos/kokkos-kernels.git)

    Test_ODE_Newton: Add template parameters for Kokkos::pair (detail)

**Comment by lucbv** [comment] 2023-09-25 17:00
Okay the issue was reproduced and I was able to identify where this issue is coming from.
The test triggering the compiler failure is `Test_Sparse_spmv_bsr.hpp`.
With the modification shown below the unit-test compiles just fine, so that's a good indication of where the problem is:
```
diff --git a/sparse/unit_test/Test_Sparse_spmv_bsr.hpp b/sparse/unit_test/Test_Sparse_spmv_bsr.hpp
index 164c87b..bc02424 100644
--- a/sparse/unit_test/Test_Sparse_spmv_bsr.hpp
+++ b/sparse/unit_test/Test_Sparse_spmv_bsr.hpp
@@ -379,13 +379,14 @@ void test_spmv_combos(const char *mode, const Bsr &a, const Crs &acrs,
   if constexpr (KokkosKernels::Impl::kk_is_gpu_exec_space<execution_space>()) {
 #if defined(KOKKOS_ENABLE_CUDA)
     if constexpr (std::is_same_v<execution_space, Kokkos::Cuda>) {
-#if defined(KOKKOS_ARCH_AMPERE) || defined(KOKKOS_ARCH_VOLTA)
-      ctrls.push_back(Ctrls({{"algorithm", "experimental_tc"}}));
-#if defined(KOKKOS_ARCH_AMPERE)
-      ctrls.push_back(Ctrls(
-          {{"algorithm", "experimental_tc"}, {"tc_precision", "double"}}));
-#endif  // AMPERE
-#endif  // AMPERE || VOLTA
+       printf("Hello!\n");
+// #if defined(KOKKOS_ARCH_AMPERE) || defined(KOKKOS_ARCH_VOLTA)
+//       ctrls.push_back(Ctrls({{"algorithm", "experimental_tc"}}));
+// #if defined(KOKKOS_ARCH_AMPERE)
+//       ctrls.push_back(Ctrls(
+//           {{"algorithm", "experimental_tc"}, {"tc_precision", "double"}}));
+// #endif  // AMPERE
+// #endif  // AMPERE || VOLTA
     }
 #endif  // CUDA
   }
@@ -617,13 +618,14 @@ void test_spm_mv_combos(const char *mode, const Bsr &a, const Crs &acrs,
   if constexpr (KokkosKernels::Impl::kk_is_gpu_exec_space<execution_space>()) {
 #if defined(KOKKOS_ENABLE_CUDA)
     if constexpr (std::is_same_v<execution_space, Kokkos::Cuda>) {
-#if defined(KOKKOS_ARCH_AMPERE) || defined(KOKKOS_ARCH_VOLTA)
-      ctrls.push_back(Ctrls({{"algorithm", "experimental_tc"}}));
-#if defined(KOKKOS_ARCH_AMPERE)
-      ctrls.push_back(Ctrls(
-          {{"algorithm", "experimental_tc"}, {"tc_precision", "double"}}));
-#endif  // AMPERE
-#endif  // AMPERE || VOLTA
+      printf("Hello!\n");
+// #if defined(KOKKOS_ARCH_AMPERE) || defined(KOKKOS_ARCH_VOLTA)
+//       ctrls.push_back(Ctrls({{"algorithm", "experimental_tc"}}));
+// #if defined(KOKKOS_ARCH_AMPERE)
+//       ctrls.push_back(Ctrls(
+//           {{"algorithm", "experimental_tc"}, {"tc_precision", "double"}}));
+// #endif  // AMPERE
+// #endif  // AMPERE || VOLTA
     }
 #endif  // CUDA
   }
```

@cwpearson do you mind having a look here, worst case scenario we can deactivate these branches with CUDA 11.0.0, however if a simple modification to the pre-processor logic can fix the problem, that would be the favored approach.

**Comment by cwpearson** [comment] 2023-09-28 21:16
Interesting, this change only disables the execution of the tensor-core tests, but they would still be compiled. Maybe I can be a bit kinder to the compiler in lines like this:
```
+//       ctrls.push_back(Ctrls(
+//           {{"algorithm", "experimental_tc"}, {"tc_precision", "double"}}));
```

**Comment by cwpearson** [comment] 2023-09-28 22:43
This seems to be a bug in CUDA 11's handling of std::optional, nothing to actually do with tensor cores.

**Comment by cwpearson** [comment] 2023-10-02 20:55
@ndellingwood this is hopefully fixed in [1983](https://github.com/kokkos/kokkos-kernels/pull/1983)

**Closed** 2023-10-09 15:12 UTC
Labels: CompilerIssue
