### ISSUE TITLE
BLAS underscore mangling

### ISSUE THREAD

**Issue by theguruat12** [kokkos/kokkos-kernels#369] opened 2019-01-14 20:07 UTC
With XL, there is no underscore added for Fortran calls from C.  Kokkos-Kernels appears to hard-code this with one underscore (which works for most compilers).

Attached is the patch that I had to implement to get it to build on the miniature version of the Sierra platform (Essentially just changing the hard-coding to not have underscores; this only changed the symbols that were referenced in my project, it will be necessary to change them for all of the externs).  I would like a configure-time option to choose the mangling, just like Trilinos does (I think it's in Teuchos).

Patch:
[0001-KokkosKernels-Change-BLAS-to-no-underscores.patch.txt](https://github.com/kokkos/kokkos-kernels/files/2756875/0001-KokkosKernels-Change-BLAS-to-no-underscores.patch.txt)

**Comment by srajama1** [comment] 2019-01-15 16:32
@kyungjoo-kim @ndellingwood Can you make this a PR  ?

**Comment by ndellingwood** [comment] 2019-01-15 18:13
@srajama1 based on the comment it looks this is a good start but more work will be necessary for a complete fix. I can help, but would like to talk with you and @kyungjoo-kim more about what is involved to support XL and not break compatibility with other compilers. Adding reference to #307 and trilinos/Trilinos#2850 (closed issues with follow-ons) that have discussion that may be relevant.

**Comment by kyungjoo-kim** [comment] 2019-01-15 21:09
This may be okay for xl but it is not okay with other compilrs like intel and gcc. To do this more correctly, we need to detect fortran mangling from the compilation level (like trilinos does). CMake can do this but I dont know how to. Anyone CMake grue might know how to. We also need help from @crtrott for the stand-alone makefile.

**Comment by mhoemmen** [comment] 2019-01-15 21:12
@kyungjoo-kim Teuchos uses some CMake logic for this.  Tpetra used to have an improved version of that CMake logic, until y'all deleted the GEMV and GEMM wrappers.  If you want me to help, I'll be happy to, but please send me an e-mail first asking specifically for what you want.

**Comment by kyungjoo-kim** [comment] 2019-01-15 21:14
@mhoemmen I appreciate if you can help for CMake. I am not sure if kokkoskernels stand alone cmake logic completes or not. @srajama1 do we have a stand alone cmake to test now ? If the work is already merged, we can start to moify the cmake logic.

**Comment by mhoemmen** [comment] 2019-01-15 21:48
@kyungjoo-kim Please send me an e-mail requesting this feature.  I will begin at that time.  Thanks!

**Comment by theguruat12** [comment] 2019-01-15 21:51
@kyungjoo-kim @mhoemmen I apologize, I should have been more clear.  What you have suggested IS what I would like kokkos to do (properly select the underscore mangling).

**Comment by mhoemmen** [comment] 2019-01-16 00:06
@theguruat12 reminded me that kokkos-kernels has a customer that needs this to work for the Makefile-based build system as well.  This shouldn't be hard -- just specify the mangling macro definition on the command line as a `-D`.  It's also a lower priority.

**Comment by mhoemmen** [comment] 2019-01-18 00:36
@kyungjoo-kim @ndellingwood I have a fix in Trilinos, in the `Fix-KokkosKernels-BLAS-mangling` branch (here, not in my fork).  It works fine with the CMake-based build system.  I made an attempt to fix it for the Makefile-based build system too, but I don't know how to test that.  Please take a look and see if it's OK.  If you think it's OK, I'll make this a kokkos-kernels PR and simultaneously a Trilinos PR.

**Comment by mhoemmen** [comment] 2019-01-19 22:59
Thanks @ndellingwood !  It really helps that we require a recent CMake; that means I can use entirely native CMake functions.

**Comment by mhoemmen** [comment] 2019-01-19 23:34
Thanks @ndellingwood for your investigations!

**Comment by kyungjoo-kim** [comment] 2019-01-21 18:57
Thank you for working on this. It seems to be quite easy to just include ``FortranCInterface``. I am okay to merge your branch to both trilinos and kokkoskernels. We will make sure the Makefile part once your submit the PR to the kokkoskernels repo. I don't really have a good idea how to detect fortran mangling from a stand alone makefile (I usually see to find fortran mangling from autoconf or cmake only). At this moment, I would just take user input regarding to the fortran mangling for the stand alone make file to generate the the mangling header file. Any better way ?

**Comment by mhoemmen** [comment] 2019-01-21 19:13
@kyungjoo-kim wrote:
> I don't really have a good idea how to detect fortran mangling from a stand alone makefile

My plan was to have sane defaults and let users override by defining Makefile variables themselves.  That's what I did in the branch.  I'm just not sure how to test it.

**Comment by kyungjoo-kim** [comment] 2019-01-21 19:15
@mhoemmen Thanks. If you don't mind, would you please submit PR for both KK and Trilinos ? From there I can take care and test it.

**Comment by mhoemmen** [comment] 2019-01-21 20:05
I'll do Trilinos first today since Sierra needs it for the next Trilinos promotion.

**Comment by mhoemmen** [comment] 2019-01-21 20:07
@kyungjoo-kim Here is the Trilinos patch: https://github.com/trilinos/Trilinos/pull/4228

**Comment by kyungjoo-kim** [comment] 2019-01-22 22:38
@theguruat12 Do you have this problem when you compile kokkoskernels with Trilinos ? Or kokkoskernels is used as stand alone ?

**Comment by kyungjoo-kim** [comment] 2019-01-22 23:15
@theguruat12 Another question. According to [XL programming guide, page 90](http://www.bluefern.canterbury.ac.nz/ucsc%20userdocs/forucscwebsite/c/aix/proguide.pdf), XL provides blas library with C interface. This is different from IBM ESSL library (this is fortran library). 

So, I am wondering if you mean that the C-interface provided from the XL compiler (-lxopt) when you say XL uses no underscore blas. If so, trilinos/Trilinos#4228 won't fix your problem as it is not a problem of fortran mangling. 

If XL indeed uses no-underscore fortran mangling, the current Trilinos won't identify such fortran mangling, either. Thus, Trilinos will not work either in that case.

**Comment by nmhamster** [comment] 2019-01-22 23:32
@kyungjoo-kim - on Page 90 it says that they only ship `dgemm`, `sgemm`, `sgemv` and `dgemv` in `libxlopt`. I imagine you want more functions than that? XL usually does not add underscores Fortran name mangling.

**Comment by kyungjoo-kim** [comment] 2019-01-22 23:35
@nmhamster I don't really mind about the functionalities but I just want to double check what is real problem in this issue. 

When I googling [examples of xlc with blas](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbcpx01/atlasexample1.htm), it uses a single underbar interface. 

So, I want to assure that XL indeed uses no-underbar fortran mangling.

**Comment by nmhamster** [comment] 2019-01-22 23:39
Example:

```
SUBROUTINE myFunction

   PRINT *, "Hello"

END SUBROUTINE
```

When compiled with XL (lower case, no underscore):

```
0000000000000000 T myfunction

```

When compiled with gfortran (lower case, with underscore):

```
0000000000000000 T myfunction_
```

**Comment by kyungjoo-kim** [comment] 2019-01-23 00:03
@nmhamster Ah................................ sounds like the problem is quite complicated. So the example I googled uses blas library complied by another compiler as it uses a single underscore. 

So, our IBM machines are equipped with OpenBLAS, LAPACK or ESSL compiled by XL, right ? Due to the different fortran interface, it might be also problematic with other third party libraries (if the TPLs uses BLAS internally and the code does not correctly deduce fortran interface). 

Ah.............. have you compiled trilinos with XL compiled BLAS ? I am wondering this because [Trilinos fortran mangling](https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/core/package_arch/TribitsFortranMangling.cmake) choose between single and double underscores if the fortran compiler is not enabled in the configuration and this is how trilinos is built for ATDM apps.

**Comment by sebrowne** [comment] 2019-01-23 14:11
@kyungjoo-kim The one I'm attempting to use was compiled with XL, thus, no underscores.

For this use case, only the CMake (as part of Trilinos) build is needed.

**Comment by kyungjoo-kim** [comment] 2019-01-24 00:33
@sebrowne Thank you.

**Closed** 2019-01-28 15:26 UTC

**Comment by trudeaun** [comment] 2019-01-30 02:06
Sorry that this is coming in late, but I wanted to make sure you saw that IBM XL Fortran offers a compiler option called `-qextname`, which adds an underscore to the end of global names, making it behave like gfortran. This option is not on by default. You can learn more about it on [Knowledge Center](https://www.ibm.com/support/knowledgecenter/en/SSAT4T_16.1.1/com.ibm.xlf1611.lelinux.doc/compiler_ref/extname.html).

**Comment by sebrowne** [comment] 2019-01-30 14:03
@trudeaun , Thank you for the information.  In this case, since I'm compiling against an _existing_ version of BLAS, I do still need the functionality of dynamically determining the mangling, but yes, if I were to compile all TPLs (including BLAS) myself, I could specify that option.
