### ISSUE TITLE
ATDM test failing in Trilinos https://github.com/trilinos/Trilinos/issues/3864

### ISSUE THREAD

**Issue by kddevin** [kokkos/kokkos-kernels#370] opened 2019-01-15 22:28 UTC
ATDM tests in Trilinos report
KokkosKernels tests randomly timing out on ATDM mutrino KNL build
https://github.com/trilinos/Trilinos/issues/3864

The issue was reported in Trilinos, but perhaps, for accurate tracking/planning, it should be noted in Kokkos-Kernels repo instead/too?

**Comment by srajama1** [comment] 2019-01-16 04:14
@kddevin The last I saw this was an environment issue. Did you hear something different ?

**Comment by srajama1** [comment] 2019-01-28 20:58
@ndellingwood Can you (or someone who has access to mutrino like @william76 ) check this one ?

**Comment by ndellingwood** [comment] 2019-01-28 21:23
Since they randomly time out I believe addressing #253 will also help here. We can look into a couple things, easiest is to see which tests are slow and reduce input sizes, maybe consider breaking up the unit tests into multiple tests so they parallelize better (not sure how this would affect Cuda builds though, I'd be a bit concerned that by parallelizing the tests we may cause more competition for GPU resources and if any of the tests are stressing upper limits of the GPU then multiple tests trying to run won't end well).

**Comment by ndellingwood** [comment] 2019-01-28 21:37
@srajama1 I'm getting a build going on mutrino (usually takes awhile) then I'll reduce sizes on the lengthier tests.

**Comment by ndellingwood** [comment] 2019-01-28 21:56
@srajama1 wait, I just looked at the report from Joe for example the OpenMP sparse unit tests, here is link to a filtered version for numbers this month [link](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=KokkosKernels_sparse_openmp_MPI_1&field3=site&compare3=61&value3=mutrino&field4=buildstarttime&compare4=84&value4=2019-01-27T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-01-01T00%3A00%3A00)

Most of the tests finish in 1 to 5 mins, but in some cases they run for 10 mins (no code changes are the cause), this must be a system issue.

**Comment by ndellingwood** [comment] 2019-02-01 06:08
Since this seems to be an environment issue on Mutrino I'm marking as won't fix, please relabel if a different option should be used.

**Comment by kddevin** [comment] 2019-02-01 16:48
Yes, of course.  Thanks!

**Comment by kddevin** [comment] 2019-02-01 16:49
Can we close the related Trilinos issue as well?

**Comment by srajama1** [comment] 2019-02-01 18:43
Thank you ! I thought Ross might want to keep it open to get the environment fixed. I will check with him on the Trilinos issue. Closing this one.

**Closed** 2019-02-01 18:43 UTC
Labels: wontfix
