### ISSUE TITLE
Build errors with cuSPARSE ON (cuda 11.2.2 and gcc 8.3.1) on Weaver

### ISSUE THREAD

**Issue by vqd8a** [kokkos/kokkos-kernels#1564] opened 2022-10-11 20:56 UTC
I see these errors when building Kokkos Kernels develop branch (Kokkos develop branch) on Weaver with cuSPARSE ON:

**Compilation error**:
```
/ascldap/users/vqdang/Kokkos/kokkos-kernels/sparse/src/KokkosSparse_spgemm_handle.hpp(238): error: identifier "cusparse_spgemm_handle_t" is undefined
```
**Reproducer** (weaver rhel8 queue):
```
module purge
module load git cmake/3.21.2 cuda/11.2.2/gcc/8.3.1 openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1

Build Kokkos:
cmake /ascldap/users/vqdang/Kokkos/kokkos -DCMAKE_CXX_COMPILER=/ascldap/users/vqdang/Kokkos/kokkos/bin/nvcc_wrapper -DCMAKE_BUILD_TYPE:STRING=RELEASE -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/ascldap/users/vqdang/Kokkos/kokkos-install-cuda-weaver -DKokkos_ENABLE_SERIAL:BOOL=ON -DKokkos_ENABLE_OPENMP:BOOL=ON -DKokkos_ARCH_POWER9=ON -DKokkos_ENABLE_CUDA:BOOL=ON -DKokkos_ENABLE_CUDA_LAMBDA:BOOL=ON -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON -DKokkos_ARCH_VOLTA70=ON

Build Kokkos Kernels:
cmake /ascldap/users/vqdang/Kokkos/kokkos-kernels -DCMAKE_CXX_COMPILER=/ascldap/users/vqdang/Kokkos/kokkos/bin/nvcc_wrapper -DCMAKE_BUILD_TYPE:STRING=RELEASE -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/ascldap/users/vqdang/Kokkos/kokkoskernels-install-cuda-weaver -DKokkos_DIR=/ascldap/users/vqdang/Kokkos/kokkos-install-cuda-weaver/lib64/cmake/Kokkos -DKokkosKernels_ENABLE_TPL_CUBLAS:BOOL=OFF -DKokkosKernels_ENABLE_TPL_CUSPARSE:BOOL=ON
```
Not sure what I am missing here?

**Comment by ndellingwood** [comment] 2022-10-11 21:33
I think related to #803 ?

**Comment by vqd8a** [comment] 2022-10-27 05:40
Just to confirm, the build errors still exist.

**Comment by brian-kelley** [comment] 2022-10-27 22:15
@vqd8a I figured out that the issue is something like this, in pseudocode:

```
#if cuda version >= 11.4:
  call the new spgemm reuse functions
#else if cuda version < 11.0:
  call the old Xcsrgemm functions
#else
  error out!
#endif
```
So version 11.2 falls in this gap where nothing is supported. It has an interface like the newest 11.x versions, it just doesn't have "reuse" in the name. I'm adding this and will have a PR very soon.

**Comment by vqd8a** [comment] 2022-10-27 22:16
Thanks @brian-kelley

**Comment by brian-kelley** [comment] 2022-10-31 17:02
@vqd8a Jim actually fixed this build error in his parILUT PR, so I'm marking this InDevelop. However, you still can't use cuSPARSE spgemm in versions 11.0-11.3 (it will just throw if you specifically request it). So I'm still going to fix that.

**Comment by brian-kelley** [comment] 2022-10-31 19:14
@ndellingwood Do we still leave issues open until the fix reaches master?

**Comment by ndellingwood** [comment] 2022-11-10 21:36
> @ndellingwood Do we still leave issues open until the fix reaches master?

@brian-kelley I'll go ahead and close this. We can close issues as they are complete, changelog entries are now pulled from the merged PRs rather than issues

**Closed by ndellingwood** 2022-11-10 21:36 UTC
Labels: InDevelop, CompatibilityUpdate

**Comment by brian-kelley** [comment] 2022-11-10 21:38
@ndellingwood Cool. I do find it more intuitive to just close issues when they're fixed in develop.
