### ISSUE TITLE
How does the partitioned-inverse sptrsv apply the best no-fill and reordered partitioning algorithm?

### ISSUE THREAD

**Issue by learning-chip** [kokkos/kokkos-kernels#1515] opened 2022-09-06 08:26 UTC
Following up #1514, but attempts to further understand the detail of the partitioned inverse algorithm. I am in need of a fast triangular solve on parallel machine so find this idea very interesting.

The [Kokkos sptrsv paper](https://dl.acm.org/doi/10.1145/3404397.3404428) refers [F. L. Alvarado, A. Pothen, and R. Schreiber. 1993. Highly Parallel Sparse Triangular Solution](https://link.springer.com/chapter/10.1007/978-1-4613-8369-7_7) for the SpMV-based implementation. That old original paper introduces several heuristics for computing the best no-fill and best reordered paritioning (Fig 2. Algorithm P1, Fig 3. Algorithm RP1, Fig 4. Algorithm RP2). Compared to the original matrix, reordering effectively reduces the number of L_i factors (Fig 1, Table 1), thus reduces the number of SpMVs.

Example and pseudocode from the paper:
<img width="779" alt="result" src="https://user-images.githubusercontent.com/80731350/188633964-33b4657d-6fe8-4aec-b73f-ef966bc78581.png">

<img width="764" alt="P1" src="https://user-images.githubusercontent.com/80731350/188633978-b904492a-0728-4262-91e9-49e94312ef95.png">

<img width="744" alt="RP1" src="https://user-images.githubusercontent.com/80731350/188634004-0acb0c89-3afc-4e83-89c6-2f6881b6d48e.png">

Looking through the Kokkos source code, the most relevant code should be inside `KokkosSparse_sptrsv_solve_impl.hpp`, the `SparseTriSupernodalSpMVFunctor` which is called when `invert_offdiagonal` is true.

**My question is:** The code seems to use the input supernodal structure (from SuperLU or Cholmod) as matrix partition, without applying the reordering & partitioning heuristics from the original Alvarado & Pothen paper. Thus the number of L_i factors might not be optimal? Do I understand it correctly or do I miss something?  Thanks!

https://github.com/kokkos/kokkos-kernels/blob/42ab7a29f33df64406ec5d7eae5c39926598ec33/src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp#L697-L779

**Comment by iyamazaki** [comment] 2022-09-06 14:59
Thank you for the bug report & interest, @learning-chip. I have not managed to reproduce the error, but am looking for potential fixes. As @srajama1 said, the code uses the no-fill partition, but it is based on the supernodal block structure (so there is no fill blocks, and if the block is full-dense, then there are no fill entries). The partitioning is computed in our symbolic phase of the solver (e.g., [here](https://github.com/kokkos/kokkos-kernels/blob/42ab7a29f33df64406ec5d7eae5c39926598ec33/src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp#L441-L568)).

**Comment by learning-chip** [comment] 2022-09-06 16:18
@srajama1 @iyamazaki  Thanks for the replies. This clarifies things!

> so I am curious about your interest

I need to solve some giant sparse matrices (>10M rows) from circuit simulation. There are many right-hand-sides to solve for a single matrix, so the bottleneck is the triangular solve phase rather than the factorization step. I am familiar with the classic level-schedule sptrsv parallelization, but its inherent data dependency limits the parallelism. So I am looking around for improvements.

The Alvarado & Pothen paper reports much better parallelism, which makes me quite curious.

<img width="707" alt="table3" src="https://user-images.githubusercontent.com/80731350/188684397-e6cb0704-22b6-4d48-ac2c-67f615907c61.png">

But I don't find any code implementation of the reordered partitioning algorithm, so cannot verify such performance gain. Since Kokkos doesn't have it either, the only way is to write the heuristics from scratch I guess :)

> I have not managed to reproduce the error,

I put an reproducible Dockerfile at https://github.com/kokkos/kokkos-kernels/issues/1514#issuecomment-1238349606

**Comment by srajama1** [comment] 2022-09-06 16:32
@learning-chip It is tough for us to use your docker files in the environment we work in.  We can try to reproduce just with the compiler options.

Since you said circuit simulation, I have to as ask this. Do you need a supernodal solver for your problem or you are using it because of our triangular solver. Some circuit problems do have the supernodal structure and some don't.  Let us make sure we get the correct L and U. If L and U are non-supernodal we could try a different approach for triangular solve.

Yes, Alvarado & Pothen report better times with different reorderings. However, take a look at the number of levels. Each level is a kernel launch from host to device. With modern accelerators, this is a trade-off we have take into account. The supernodal option reduces this by launching kernels for a set of columns (supernodes). In addition to local compute efficiency (because of dense blocks) this reduction in number of kernel launches will also help. Does that help?

**Comment by iyamazaki** [comment] 2022-09-06 22:02
Thank you for the info, @learning-chip. @srajama1 knows these better, but doesn't Cholmod support a few matrix ordering schemes? 

Right, we don't see much supernodal structures in many of our circuit matrices (though some of them does), and they are non-symmetric, I think. I am curious, is Cholmod's factorization running much faster than KLU's in SuiteSparse (though KLU is non-symmetric, it often works well with circuit structures)?

**Comment by learning-chip** [comment] 2022-09-07 01:46
> but doesn't Cholmod support a few matrix ordering schemes?

Cholmod's reordering is for the symmetric matrix A (to reduce fill-in), while the Alvarado paper's reordering heuristic is for the triangular matrix L I think. The two stages are independent of each other. They combined MMD/MLMD reordering of A with the proposed RP1/RP2 reordering of L.

> they are non-symmetric, I think. I am curious, is Cholmod's factorization running much faster than KLU's in SuiteSparse

The KCL/KVL law can be formulated in an SPD way as in [this paper](https://dl.acm.org/doi/abs/10.1145/2429384.2429526), so suitable for Cholesky. The paper also shows Cholmod to be faster than KLU (Table 2)

**Comment by learning-chip** [comment] 2022-09-07 02:05
> Some circuit problems do have the supernodal structure and some don't.

That's right. Supernode pays off for certain circuits but not all. The [Cholmod paper](https://dl.acm.org/doi/10.1145/1391989.1391995) uses ops/nnz(L) as a metric to turn on/off supernode (Section 3.1.2 "Supernodal/Nonsupernodal Tradeoff."). This is consistent with my experiments.

> The supernodal option reduces this by launching kernels for a set of columns (supernodes).

If I understand it correctly -- using the supernodal structure as inverse partitioning is a sufficient but not necessary condition for no-fill-in partition:
- Sufficiency: Each supernodal column can be view as an "elementary block triangular matrix" that can be "inverted in-place" if we view the offdiag-block as a "big element". This is a generalization of elementary triangular matrix.
- Non-necessity: By further applying the heuristic P1/RP1/RP2 from the original paper, it is possible to further reduce the number of L_i factors, thus even less kernel launches needed.

Of course, without actually implementing the P1/RP1/RP2 algorithm, I can't make any conclusion now. Maybe using the supernodal structure as did in Kokkos is good enough, or maybe there's room for improvement.

**Comment by srajama1** [comment] 2022-09-07 02:32
> The KCL/KVL law can be formulated in an SPD way as in [this paper](https://dl.acm.org/doi/abs/10.1145/2429384.2429526), so suitable for Cholesky. The paper also shows Cholmod to be faster than KLU (Table 2)

I wasn't aware of this paper. Thanks!

> using the supernodal structure as inverse partitioning is a sufficient but not necessary condition for no-fill-in partition:

You are correct. I don't know what you mean by "big element" as the off-diagonal blocks within a supernode is not fully dense, but just block dense. 

> By further applying the heuristics P1/RP1/RP2 from the original paper, it is possible to further reduce the number of L_i factors, thus even less kernel launches needed.

Yes, if you generalize the ordering heuristics in the original paper to a supernodal L matrix, **I think** one could reorder to arrive at even better orderings just for L. This is an interesting question to explore. 

**I think** the ordering code can be implemented independent of the solve and the current solver could be called on the reordered matrix. @iyamazaki knows if the implementation can handle this. 

If you choose to implement these orderings, do contribute back to our code if you can.

**Comment by iyamazaki** [comment] 2022-09-07 03:46
Thank you for the reference, @learning-chip. That is really nice you end up with an SPD matrix, and Cholmod performs well. It will be really cool if you get speedup using partitioned inverse. Yes, we can order the matrix in anyway you like before calling Cholmod/SuperLU. And, yes, it may be interesting to explore, there seems to be some trade off between reducing the number of levels and fills (for exact factorization)? Currently, we use nested-dissection which seems to have nice trade-off between reducing fills and exposing parallelism.

**Comment by iyamazaki** [comment] 2022-09-12 03:58
Thank you, @learning-chip. This has been a nice discussion. I'll close this for now. Let us know if you have any other comments, or how our code worked out. There is also Amesos2 interface in Trilinos that gives interface to different spares direct solvers including Cholmod, or Tachos which computes Cholesky on a GPU, and has a similar sparse-triangular solve option.

**Closed by iyamazaki** 2022-09-12 03:58 UTC
