### ISSUE TITLE
Alias CMake library name as `KokkosKernels::kokkoskernels`

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos-kernels#1749] opened 2023-03-21 23:39 UTC
Add the proper alias `KokkosKernels::kokkoskernels` to match what it's exported as from Trilinos (and what it ought to be), and deprecate the `Kokkos::kokkoskernels` alias

**Comment by PhilMiller** [comment] 2023-03-21 23:40
From Slack discussion with @dalg24, who asked @lucbv to take care of it. It would be nice if this were integrated into the 4.0.1 release @ndellingwood

**Comment by ndellingwood** [comment] 2023-03-22 17:02
Cross-referencing #869 , which looks like it may be related

**Comment by ndellingwood** [comment] 2023-03-23 04:02
Thanks @PhilMiller for confirmation for the update

From a review of the connected Trilinos issue, TriBITs has been updated to allow for the needed support, but what isn't clear to me from the comment at https://github.com/trilinos/Trilinos/issues/8866#issuecomment-796969671 and the original post is the path forward for target convention - that is `KokkosKernels::all_libs` vs `KokkosKernels::kokkoskernels`

**Comment by PhilMiller** [comment] 2023-03-29 21:29
Ping on this - just adding the corrected name as an alias in Kernels would resolve this issue

**Comment by ndellingwood** [comment] 2023-06-07 22:54
PR #1855 up to add the `KokkosKernels::kokkoskernels` alias, will be part of the 4.1 release

**Comment by ndellingwood** [comment] 2023-06-08 22:23
PR #1855 merged

**Comment by PhilMiller** [comment] 2023-07-05 00:43
Ugh, it seems that the change in #1855 is insufficient, at least in the non-trilinos standalone-installed case, because
["`ALIAS` targets are not mutable, installable or exportable. They are entirely local to the buildsystem description"](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#alias-targets)

In the downstream code that does `find_package(Kokkos)` and `find_package(KokkosKernels)`, when I [print the imported targets](https://stackoverflow.com/questions/45479456/cmake-is-there-a-way-to-get-a-list-of-imported-targets-that-belong-to-a-package), I get 
```
Imported targets: Kokkos::LIBDL;Kokkos::kokkoscore;Kokkos::kokkoscontainers;Kokkos::kokkosalgorithms;Kokkos::kokkossimd;Kokkos::kokkos;Kokkos::kokkoskernels
```

**Comment by PhilMiller** [comment] 2023-07-05 01:02
I think the actual 'issue' would be addressed by

```diff
diff --git a/cmake/kokkoskernels_tribits.cmake b/cmake/kokkoskernels_tribits.cmake
index 2d70f656a..40f0edae0 100644
--- a/cmake/kokkoskernels_tribits.cmake
+++ b/cmake/kokkoskernels_tribits.cmake
@@ -32,7 +32,7 @@ MACRO(KOKKOSKERNELS_PACKAGE_POSTPROCESS)
 
     INSTALL(EXPORT KokkosKernelsTargets
             DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/KokkosKernels
-            NAMESPACE Kokkos::)
+            NAMESPACE KokkosKernels::)
   ENDIF()
 ENDMACRO(KOKKOSKERNELS_PACKAGE_POSTPROCESS)
 ```

Unfortunately, it looks like the that will necessarily break packages that were explicitly using the older form `Kokkos::kokkoskernels`

**Comment by PhilMiller** [comment] 2023-07-05 01:06
And of course, [searching GitHub turns up a number of such projects](https://github.com/search?q=Kokkos%3A%3Akokkoskernels&type=code)

I may end up recommending this downstream:
```cmake
    if(TARGET KokkosKernels::kokkoskernels)
      target_link_libraries(${CHECKPOINT_LIBRARY} PUBLIC KokkosKernels::kokkoskernels)
    else()
      target_link_libraries(${CHECKPOINT_LIBRARY} PUBLIC Kokkos::kokkoskernels)
    endif()
```

**Comment by ndellingwood** [comment] 2023-10-25 01:08
Reopening and cross-referencing https://github.com/trilinos/Trilinos/issues/12002

**Comment by ndellingwood** [comment] 2023-10-25 01:12
To test Trilinos with external builds of Kokkos and KokkosKernels, I first tried this change to KokkosKernels pattern matching https://github.com/kokkos/kokkos/pull/6157:

```diff
diff --git a/cmake/KokkosKernelsConfig.cmake.in b/cmake/KokkosKernelsConfig.cmake.in
index fbceffe76..409fb9061 100644
--- a/cmake/KokkosKernelsConfig.cmake.in
+++ b/cmake/KokkosKernelsConfig.cmake.in
@@ -11,3 +11,12 @@ find_dependency(Kokkos HINTS @Kokkos_DIR@)
 
 INCLUDE("${KokkosKernels_CMAKE_DIR}/KokkosKernelsTargets.cmake")
 
+IF(NOT TARGET KokkosKernels::all_libs)
+  # CMake Error at <prefix>/lib/cmake/Kokkos/KokkosConfigCommon.cmake:10 (ADD_LIBRARY):
+  #   ADD_LIBRARY cannot create ALIAS target "Kokkos::all_libs" because target
+  #   "KokkosKernels::kokkoskernels" is imported but not globally visible.
+  IF(CMAKE_VERSION VERSION_LESS "3.18")
+    SET_TARGET_PROPERTIES(KokkosKernels::kokkoskernels PROPERTIES IMPORTED_GLOBAL ON)
+  ENDIF()
+  ADD_LIBRARY(KokkosKernels::all_libs ALIAS KokkosKernels::kokkoskernels)
+ENDIF()
```

That was not sufficient because I still ran into the same issue @PhilMiller mentioned above https://github.com/kokkos/kokkos-kernels/issues/1749#issuecomment-1620877644
```
CMake Error at /Users/ndellin/Research/KokkosEco/Trilinos_External_TPL/install_kokkos-kernels/lib/cmake/KokkosKernels/KokkosKernelsConfig.cmake:45 (ADD_LIBRARY):
  ADD_LIBRARY cannot create ALIAS target "KokkosKernels::all_libs" because
  target "KokkosKernels::kokkoskernels" does not already exist.
```

I tested the additional change to the namespace (which is not backward compatible) and this allowed me to successfully configure Trilinos (serial build) with external KokkosKernels:
```diff
diff --git a/cmake/kokkoskernels_tribits.cmake b/cmake/kokkoskernels_tribits.cmake
index 2d70f656a..49db16dbb 100644
--- a/cmake/kokkoskernels_tribits.cmake
+++ b/cmake/kokkoskernels_tribits.cmake
@@ -32,7 +32,7 @@ MACRO(KOKKOSKERNELS_PACKAGE_POSTPROCESS)
 
     INSTALL(EXPORT KokkosKernelsTargets
             DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/KokkosKernels
-            NAMESPACE Kokkos::)
+            NAMESPACE KokkosKernels::)
   ENDIF()
 ENDMACRO(KOKKOSKERNELS_PACKAGE_POSTPROCESS)
```

I'm not sure how to handle the necessary change in a backward-compatible way, and as @PhilMiller pointed out there would be impact on downstream codes with such a change. @lucbv @bartlettroscoe any suggestions?

**Comment by bartlettroscoe** [comment] 2023-10-25 14:03
@ndellingwood, the solution for this should be the same as it was for Kokkos and is described in:

* https://tribitspub.github.io/TriBITS/users_guide/index.html#how-to-implement-a-tribits-compliant-external-package-using-raw-cmake

The problem is, how do I drive the testing of this with Trilinos?  Is the development version of Kokkos and KokkosKernels compatible with Trilinos 'develop', when building Kokkos and KokkosKernels as part Trilinos (i.e. using `-D KokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernles`)?  If I know that works, then getting Triinos to build against an external install of KokkosKernels should be pretty straightforward.  If not, then this is much harder to do (which is what I had to go through with Kokkos).

**Comment by ndellingwood** [comment] 2023-10-25 18:18
@bartlettroscoe I was wondering about how best to maintain backward compatibility regarding some needed namespace changes to support the addition of the all_libs target. I put in a PR #2017 as a starter to try and handle this.

Regarding the testing with each repo's develop branches, the status is currently as in previous discussion - you may encounter periods of breakage during a release cycle. Frameworks has made progress adding nightly integration testing (tracked in TRILINOS-361), so we may be at a point to revisit your suggested path forward to improve the process in Jira issue SEPW-543, in particular the creation of mirror kokkos and kokkos-kernels repos tracking "accepted" develop branches (which would help address the problems you mentioned)

**Comment by bartlettroscoe** [comment] 2023-10-25 20:37
> @bartlettroscoe I was wondering about how best to maintain backward compatibility regarding some needed namespace changes to support the addition of the all_libs target. I put in a PR #2017 as a starter to try and handle this.

@ndellingwood, you can provide the ALIAS targets `KokkosKernels::kokkoskernels` and `KokkosKernels::all_libs` in both the current CMake project and in the installed `KokkosKernelsConfig.cmake` file.

> Regarding the testing with each repo's develop branches, the status is currently as in previous discussion - you may encounter periods of breakage during a release cycle. Frameworks has made progress adding nightly integration testing (tracked in TRILINOS-361), so we may be at a point to revisit your suggested path forward to improve the process in Jira issue SEPW-543, in particular the creation of mirror kokkos and kokkos-kernels repos tracking "accepted" develop branches (which would help address the problems you mentioned)

The sooner the better.  Otherwise, all of the Git gymnastics you have to do working with older versions of these repos creates a lot of overhead and complexity.

**Comment by lucbv** [comment] 2023-10-25 20:44
Yes, that is the option we have chosen, we will provide all past targets, i.e. `Kokkos::kokkoskernels` and `KokkosKernels::kokkoskernels` but will also are adding `KokkosKernels::all_libs`.
We have no clear deprecation plan for any of them at the moment but if we did it would be on a long time scale.

**Closed** 2023-11-27 18:17 UTC
Labels: InDevelop

**Comment by PhilMiller** [comment] 2023-11-27 23:20
It looks like #2020 was the eventual fix for this.

**Comment by lucbv** [comment] 2023-11-27 23:44
That is correct, we added this recently. If downstream apps are having issues with the new targets please let us know!
