### ISSUE TITLE
Perlmutter: Could NOT find TPLCUBLAS (missing: CUDA_CUBLAS_LIBRARIES)

### ISSUE THREAD

**Issue by jczhang07** [kokkos/kokkos-kernels#1376] opened 2022-03-30 16:04 UTC
On Perlmutter at NERSC, I could not build KK with TPL, even with correct library paths like

```
-DKokkosKernels_CUBLAS_ROOT=/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/math_libs/11.5 
-DKokkosKernels_CUSPARSE_ROOT=/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/math_libs/11.5
```
I had `cudatoolkit/11.5, cmake/3.22.0`. The error message was

```
-- Found CUDA: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5 (found version "11.5")
-- Configuring incomplete, errors occurred!
See also "/global/u1/j/jczhang/petsc/arch-kokkos-dbg/externalpackages/git.kokkos-kernels/petsc-build/CMakeFiles/CMakeOutput.log".CMake Warning at /global/homes/j/jczhang/petsc/arch-kokkos-dbg/lib/cmake/Kokkos/KokkosConfigCommon.cmake:34 (MESSAGE):
  The installed Kokkos configuration does not support CXX extensions.
  Forcing -DCMAKE_CXX_EXTENSIONS=Off
Call Stack (most recent call first):
  /global/homes/j/jczhang/petsc/arch-kokkos-dbg/lib/cmake/Kokkos/KokkosConfig.cmake:56 (INCLUDE)
  CMakeLists.txt:109 (FIND_PACKAGE)


  CMake Error at /global/common/software/nersc/pm-2021q4/sw/cmake-3.22.0/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find TPLCUBLAS (missing: CUDA_CUBLAS_LIBRARIES)
Call Stack (most recent call first):
  /global/common/software/nersc/pm-2021q4/sw/cmake-3.22.0/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindTPLCUBLAS.cmake:13 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/kokkoskernels_tpls.cmake:376 (FIND_PACKAGE)
  cmake/kokkoskernels_tpls.cmake:495 (KOKKOSKERNELS_IMPORT_TPL)
  CMakeLists.txt:196 (INCLUDE)
```

**Comment by sblondel** [comment] 2022-04-28 21:46
I have exactly the same error on Swing at ANL with `1) nvhpc/21.5-oxhtyof   2) cmake/3.21.1-e5i6eks` .

**Comment by lucbv** [comment] 2022-04-29 15:12
I'll go check what happens on Perlmutter, thanks for reporting this

**Comment by cwpearson** [comment] 2022-05-04 18:42
Hi,

I'm able to build the current Kokkos Kernels develop on perlmutter in the following configuration:

```
export CUDAARCHS="80" # for cmake 3.20+
export MPICH_GPU_SUPPORT_ENABLED=1
export CRAY_ACCEL_TARGET=nvidia80

export NVCC_WRAPPER_DEFAULT_COMPILER=CC

module load PrgEnv-gnu
module load cmake/3.22.0
module load cudatoolkit
module load cpe-cuda
```

`NVCC_WRAPPER` should be the path to kokkos/bin/nvcc_wrapper
```
cmake .. \
-DCMAKE_CXX_COMPILER=${NVCC_WRAPPER} \
-DCMAKE_BUILD_TYPE=Release \
-DKokkos_ENABLE_HWLOC=Off \
-DKokkosKernels_INST_COMPLEX_FLOAT=OFF \
-DKokkosKernels_INST_DOUBLE=ON \
-DKokkosKernels_INST_FLOAT=ON \
-DKokkosKernels_INST_OFFSET_INT=OFF \
-DKokkosKernels_ENABLE_TESTS=ON \
-DKokkos_ARCH_AMPERE80=ON \
-DKokkos_ENABLE_CUDA=ON \
-DKokkosKernels_ENABLE_TPL_CUBLAS=ON \
-DKokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=OFF
```

I get a section of the CMake output that looks like this:
```
=======================
KokkosKernels ETI Types
   Devices:  <Cuda,CudaSpace>;<Serial,HostSpace>
   Scalars:  double;float
   Ordinals: int
   Offsets:  size_t
   Layouts:  LayoutLeft

KokkosKernels TPLs
   CUBLAS:      /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/profilers/Nsight_Compute/../../math_libs/11.5/lib64/libcublas.so
   CUSPARSE:    /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/profilers/Nsight_Compute/../../math_libs/11.5/lib64/libcusparse.so
=======================
```

**Comment by sblondel** [comment] 2022-05-11 19:49
I don't have access to Perlmutter myself, if @jczhang07 could try it that would be great.

@cwpearson where you able to reproduce our issue first or did you manage to build Kokkos Kernels immediately?

**Comment by sblondel** [comment] 2022-05-19 20:22
I now have access to Perlmutter and tried compiling Kokkos Kernels with the same modules, same export variables, same options, but I still get the same error:
`-- Cray Programming Environment 2.7.15 CXX
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: KokkosKernels
-- Enabled Kokkos devices: CUDA;SERIAL
CMake Warning at /global/homes/s/sblondel/perlmutter_install/kokkos_cuda/lib64/cmake/Kokkos/KokkosConfigCommon.cmake:34 (MESSAGE):
  The installed Kokkos configuration does not support CXX extensions.
  Forcing -DCMAKE_CXX_EXTENSIONS=Off
Call Stack (most recent call first):
  /global/homes/s/sblondel/perlmutter_install/kokkos_cuda/lib64/cmake/Kokkos/KokkosConfig.cmake:62 (INCLUDE)
  CMakeLists.txt:109 (FIND_PACKAGE)


-- Found Kokkos at /global/homes/s/sblondel/perlmutter_install/kokkos_cuda/lib64/cmake/Kokkos
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5 (found version "11.5") 
CMake Error at /global/common/software/nersc/pm-2021q4/sw/cmake-3.22.0/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TPLCUBLAS (missing: CUDA_CUBLAS_LIBRARIES)
Call Stack (most recent call first):
  /global/common/software/nersc/pm-2021q4/sw/cmake-3.22.0/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindTPLCUBLAS.cmake:13 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/kokkoskernels_tpls.cmake:376 (FIND_PACKAGE)
  cmake/kokkoskernels_tpls.cmake:495 (KOKKOSKERNELS_IMPORT_TPL)
  CMakeLists.txt:196 (INCLUDE)
`

**Comment by jczhang07** [comment] 2022-10-21 16:11
I still met the same error today with updated Perlmutter default settings.

**Comment by cwpearson** [comment] 2024-02-20 19:37
I think this is a related PR: https://github.com/kokkos/kokkos-kernels/pull/2098 (just linking here for cross-reference)

**Comment by cwpearson** [comment] 2024-02-20 19:40
Probably this PR actually fixed this issue: https://github.com/kokkos/kokkos-kernels/pull/2075

**Comment by cwpearson** [comment] 2024-02-20 20:42
Closing after communication on slack

**Closed by cwpearson** 2024-02-20 20:42 UTC
